// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEBAPI.Infrastructure;

#nullable disable

namespace WEBAPI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEBAPI.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Active Wear - Men",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Active Wear - Women",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Mineral Water",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Publications",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Supplements",
                            TotalRecords = 0
                        });
                });

            modelBuilder.Entity("WEBAPI.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7596),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Grunge Skater Jeans",
                            Price = 68m,
                            Sku = "AWMGSJ",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7605),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Polo Shirt",
                            Price = 35m,
                            Sku = "AWMPS",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7608),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Skater Graphic T-Shirt",
                            Price = 33m,
                            Sku = "AWMSGT",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7610),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Slicker Jacket",
                            Price = 125m,
                            Sku = "AWMSJ",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7612),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Thermal Fleece Jacket",
                            Price = 60m,
                            Sku = "AWMTFJ",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7616),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Unisex Thermal Vest",
                            Price = 95m,
                            Sku = "AWMUTV",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7619),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "V-Neck Pullover",
                            Price = 65m,
                            Sku = "AWMVNP",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7622),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "V-Neck Sweater",
                            Price = 65m,
                            Sku = "AWMVNS",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7624),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "V-Neck T-Shirt",
                            Price = 17m,
                            Sku = "AWMVNT",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7627),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Bamboo Thermal Ski Coat",
                            Price = 99m,
                            Sku = "AWWBTSC",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            IsDeleted = false,
                            Name = "Cross-Back Training Tank",
                            Price = 0m,
                            Sku = "AWWCTT",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7632),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Grunge Skater Jeans",
                            Price = 68m,
                            Sku = "AWWGSJ",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7634),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Slicker Jacket",
                            Price = 125m,
                            Sku = "AWWSJ",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7637),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Stretchy Dance Pants",
                            Price = 55m,
                            Sku = "AWWSDP",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7639),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Ultra-Soft Tank Top",
                            Price = 22m,
                            Sku = "AWWUTT",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7641),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Unisex Thermal Vest",
                            Price = 95m,
                            Sku = "AWWUTV",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7644),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "V-Next T-Shirt",
                            Price = 17m,
                            Sku = "AWWVNT",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7648),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Blueberry Mineral Water",
                            Price = 2.8m,
                            Sku = "MWB",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7650),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Lemon-Lime Mineral Water",
                            Price = 2.8m,
                            Sku = "MWLL",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7653),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Orange Mineral Water",
                            Price = 2.8m,
                            Sku = "MWO",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7655),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Peach Mineral Water",
                            Price = 2.8m,
                            Sku = "MWP",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7657),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Raspberry Mineral Water",
                            Price = 2.8m,
                            Sku = "MWR",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7659),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Strawberry Mineral Water",
                            Price = 2.8m,
                            Sku = "MWS",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7661),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "In the Kitchen with H+ Sport",
                            Price = 24.99m,
                            Sku = "PITK",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7664),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Calcium 400 IU (150 tablets)",
                            Price = 9.99m,
                            Sku = "SC400",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7666),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Flaxseed Oil 100 mg (90 capsules)",
                            Price = 12.49m,
                            Sku = "SFO100",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 5,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7669),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Iron 65 mg (150 caplets)",
                            Price = 13.99m,
                            Sku = "SI65",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 5,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7671),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Magnesium 250 mg (100 tablets)",
                            Price = 12.49m,
                            Sku = "SM250",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 5,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7673),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Multi-Vitamin (90 capsules)",
                            Price = 9.99m,
                            Sku = "SMV",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 5,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7675),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Vitamin A 10,000 IU (125 caplets)",
                            Price = 11.99m,
                            Sku = "SVA",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 5,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7678),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Vitamin B-Complex (100 caplets)",
                            Price = 12.99m,
                            Sku = "SVB",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 5,
                            CreateDate = new DateTime(2023, 12, 19, 8, 49, 30, 252, DateTimeKind.Utc).AddTicks(7680),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Vitamin C 1000 mg (100 tablets)",
                            Price = 9.99m,
                            Sku = "SVC",
                            TotalRecords = 0
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 5,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Vitamin D3 1000 IU (100 tablets)",
                            Price = 12.49m,
                            Sku = "SVD3",
                            TotalRecords = 0
                        });
                });

            modelBuilder.Entity("WEBAPI.Domain.Entities.Product", b =>
                {
                    b.HasOne("WEBAPI.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WEBAPI.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
